---

# Based on this access.redhat.com article:
#    http://tinyurl.com/jytvxl6

- name: Create images for spare disks
  command: >
    qemu-img create -f raw {{ spare_disk_location }}/{{ item.name }}.img {{ spare_disk_size_megs }}M
  args:
    creates: "{{ spare_disk_location }}/{{ item.name }}.img"
  with_items: "{{ virtual_machines }}"

- name: Attach disk
  shell: >
    virsh attach-disk "{{ item.name }}" {{ spare_disk_location }}/{{ item.name }}.img vdb --cache none &&
    touch {{ spare_disk_location }}/.attached-{{ item.name }}
  args:
    creates: "{{ spare_disk_location }}/.attached-{{ item.name }}"
  with_items: "{{ virtual_machines }}"
