- name: "Disable SELinux :("
  selinux:
    state: disabled

- name: Install haproxy
  package:
    name: haproxy
    state: present

- name: check if haproxy config file exist
  stat:
    path: /etc/haproxy/haproxy.cfg
  register: file_status
  delegate_to: localhost

- name: backup original
  copy:
    src: /etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg.orig
  when: file_status.stat.exists

- name: create haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: start haproxy
  systemd:
    name: haproxy.service
    state: started
    enabled: yes
