---

# ----------- If the restart has happened to recently
#             We need to wait for kubectl to return with a success.

- name: Wait until kubectl get pods is ready
  shell: >
    kubectl get pods --all-namespaces
  environment: "{{ kubectl_environment }}"
  register: get_pods_result
  until: get_pods_result.rc == 0
  retries: 60
  delay: 3
  ignore_errors: yes

# ----------- flannel
- name: Apply the flannel RBAC
  shell: >
    kubectl create -f /etc/flannel-rbac.yaml
  args:
    creates: "{{ kubectl_home }}/.kubeadm-podnetwork-complete"
  when: pod_network_type == "flannel" or pod_network_type == "multus"

- name: Apply the flannel podnetwork
  shell: >
    kubectl apply -f /etc/flannel.yaml > /tmp/podnetwork-apply.log
  args:
    creates: "{{ kubectl_home }}/.kubeadm-podnetwork-complete"
  when: pod_network_type == "flannel"


# ----------- weave
- name: Apply the weave podnetwork
  shell: >
    kubectl apply -f https://git.io/weave-kube > /tmp/podnetwork-apply.log
  args:
    creates: "{{ kubectl_home }}/.kubeadm-podnetwork-complete"
  when: pod_network_type == "weave"

# ----------- multus
- name: Apply the multus podnetwork
  shell: >
    kubectl apply -f /etc/multus.yaml > /tmp/podnetwork-apply.log
  args:
    creates: "{{ kubectl_home }}/.kubeadm-podnetwork-complete"
  when: pod_network_type == "multus" and not multus_use_crd

- name: Apply the multus podnetwork (CRD style)
  shell: >
    kubectl apply -f /etc/multus-crd.yaml > /tmp/podnetwork-apply.log
  args:
    creates: "{{ kubectl_home }}/.kubeadm-podnetwork-complete"
  when: pod_network_type == "multus" and multus_use_crd


# ----------- all network types
- name: Mark podnetwork applied
  file:
    path: "{{ kubectl_home }}/.kubeadm-podnetwork-complete"
    state: directory
  when: pod_network_type != "none"

# --------------------------------------------------------------
# --------------- This didn't work because it's not scheduled.
# --------------- because no nodes were joined yet.
# --------------------------------------------------------------
# - name: Wait until the kube-dns pod is up and running
#   shell: >
#     kubectl get pods --all-namespaces | grep -P "kube-dns.+4/4.+Running"
#   register: kube_dns_result
#   until: kube_dns_result.rc == 0
#   retries: 60
#   delay: 3
#   ignore_errors: yes
#   when: pod_network_type != "none"
