- name: update kernel
  block:
    - name: rpm import
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    - name: install elrepo
      yum:
        name: https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm
        state: present
    - name: install kernel-ml
      yum:
        name: kernel-ml
        enablerepo: elrepo-kernel
        state: present
    - name: update grub default conf
      lineinfile:
        regexp: "GRUB_DEFAULT=saved"
        dest: /etc/default/grub
        line: "GRUB_DEFAULT=0"
    - name: update grub conf
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
    - name: "reboot machine"
      reboot:
        reboot_timeout: 600
  when: ansible_kernel is  version('4.6','<')

- name: install openvswitch and required dependencies on the master/worker nodes
  block:
    - name: install openstack repo
      yum_repository:
        name: openstack-train
        description: openstack-train
        file: openstack-train
        baseurl: http://mirror.centos.org/centos/7/cloud/x86_64/openstack-train/
        gpgcheck: no
    - name: install openvswitch
      yum:
        name:
          - openvswitch
        enablerepo: openstack-train
        state: present
    - name: install libibverbs
      yum:
        name: libibverbs
        state: present
    - name: enable epel
      yum:
        name: epel-release
        state: present
    - name: enable python-pip
      yum:
        name: python-pip
        state: present
        enablerepo: epel

- name: install git
  yum:
    name: git
    state: present

