---
- name: Set path to artifacts
  set_fact:
    artifact_path: "{{ ansible_env.HOME }}/src/go/src/k8s.io/kubernetes/bazel-bin/build"

- name: Instantiate artifact list
  set_fact:
    artifact_list: []

- name: Check if artifact is available
  stat:
    path: "{{ artifact_path }}/{{ item }}"
  register: artifacts_stat_list
  with_items: "{{ archive_list }}"

- name: Add to artifact list if it exists
  set_fact:
    artifact_list: "{{ artifact_list }} + [ '{{ artifact_path }}/{{ item.item }}' ]"
  with_items: "{{ artifacts_stat_list.results }}"
  when: item.stat.exists

- name: Notify of any missing artifacts
  fail:
    msg: Missing artifact {{ item.item }}
  with_items: "{{ artifacts_stat_list.results }}"
  when: not item.stat.exists
  ignore_fail: True

- name: Synchronize artifacts to kubernetes cluster
  synchronize:
    src: "{{ item }}"
    dest: "/tmp/k8s_artifacts/"
    mode: pull
  delegate_to: "{{ k8s_hostname }}"
  with_items: "{{ artifact_list }}"
  tags:
    - sync_artifacts
