---

- name: Create folder for Multus resource defs
  file:
    path: "{{ ansible_env.HOME }}/multus-resources"
    state: directory

- name: Default legacy prefix for Multus
  set_fact:
    multus_legacy_prefix: ""

- name: Set legacy prefix when using legacy version of Multus
  set_fact: 
    multus_legacy_prefix: "legacy."
  when: "multus_legacy"

- name: Template multus resources
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/multus-resources/{{ item.dest }}"
  with_items:
    - src: crd.yml.j2
      dest: "multus-crd.yml"
    - src: "{{ multus_legacy_prefix }}flannel.yml.j2"
      dest: "flannel.yml"
    - src: "{{ multus_legacy_prefix }}macvlan.yml.j2"
      dest: "macvlan.yml"
    - src: clusterrole.yml.j2
      dest: "clusterrole.yml"

- name: Check to see if CRD is present
  shell: >
    kubectl get crd
  register: check_crd

- name: Create network namespace
  set_fact:
    use_network_namespace: "network.{{ crd_namespace }}"

- name: Create base CRD
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/multus-crd.yml
  when: "use_network_namespace not in check_crd.stdout"

- name: Check to see which network CRD definitions are present
  shell: >
    kubectl get network
  register: check_network_crds

- name: Create flannel network CRD
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/flannel.yml
  when: "'flannel-conf' not in check_network_crds.stdout"

- name: Create macvlan network CRD
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/macvlan.yml
  when: "'macvlan-conf' not in check_network_crds.stdout"

- name: Check to see which CRDs are present, for validation
  shell: >
    kubectl get network
  register: verify_network_crd

- name: Verify which network CRD definitions are present
  fail: 
    msg: "The {{ item }} CRD was not present."
  when: "item not in verify_network_crd.stdout"
  with_items:
    - 'macvlan-conf'
    - 'flannel-conf'

- name: Get the clusteroles
  shell: >
    kubectl get clusterroles
  register: output_clusterroles

- name: Create clusterrole
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/clusterrole.yml
  when: >
    "multus-crd-overpowered" not in output_clusterroles.stdout

- name: Get the clusterrolebindings
  shell: >
    kubectl get clusterrolebindings
  register: output_crb

- name: Create clusterrolebindings for each machine
  shell: >
    kubectl create clusterrolebinding multus-node-{{ hostvars[item]['inventory_hostname'] }}
    --clusterrole=multus-crd-overpowered
    --user=system:node:{{ hostvars[item]['inventory_hostname'] }}
  with_items:
    - "{{ groups['nodes'] + groups['master'] }}"
  when: >
    "hostvars[item]['inventory_hostname']" not in output_crb.stdout