---
- name: Check Golang version
  shell: /usr/local/go/bin/go version
  register: go_version
  failed_when: false
  changed_when: false

- name: install Golang upstream
  unarchive:
    src: "https://golang.org/dl/go1.8.3.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: True
  when: '"go1.8.3" not in go_version.stdout'

- name: Set custom Golang path in RHEL/CentOS/Fedora
  lineinfile:
    dest: /root/.bashrc
    line: 'export PATH=/usr/local/go/bin:$PATH'
    insertafter: 'EOF'
    regexp: 'export PATH=\/usr\/local\/go\/bin:\$PATH'
    state: present
  # when: ansible_distribution in ['Fedora', 'RedHat', 'CentOS']
