---
# Some (lots!) borrowed from https://github.com/cri-o/cri-o-ansible

- name: Create a path for us
  set_fact:
    extended_path: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/centos/.local/bin:/home/centos/bin/:/usr/local/go/bin"

- name: link golang
  file: src=/usr/local/go/bin/go dest=/usr/bin/go state=link

- name: Install required packages for cri-o
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - git
    - make
    - gcc
    - tar
    - libseccomp-devel
    - golang
    - go-md2man
    - glib2-devel
    - glibc-static
    - container-selinux
    - btrfs-progs-devel
    - device-mapper-devel
    - glibc-devel
    - gpgme-devel
    - libassuan-devel
    - libgpg-error-devel
    - pkgconfig
    - json-glib-devel
    - skopeo-containers
    - ostree
    - ostree-devel
    - iptables

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
       - /usr/local/go
       - /etc/systemd/system/kubelet.service.d/
       - /var/lib/etcd
       - /etc/cni/net.d
       - /etc/containers

- name: clone runc
  git:
    repo: https://github.com/opencontainers/runc
    dest: /root/src/github.com/opencontainers/runc
    version: master

- name: clone CRI-O
  git:
    repo: https://github.com/kubernetes-incubator/cri-o
    dest: /root/src/github.com/kubernetes-incubator/cri-o
    version: "{{ crio_version }}"

- name: clone CNI
  git:
    repo: https://github.com/containernetworking/plugins
    dest: /root/src/github.com/containernetworking/plugins
    version: master

- name: build runc
  shell: |
          cd /root/src/github.com/opencontainers/runc && \
          export GOPATH=/root && \
          make BUILDTAGS="seccomp selinux" && \
          make install
  environment:
    PATH: "{{ extended_path }}"

- name: link runc
  file: src=/usr/local/sbin/runc dest=/usr/bin/runc state=link

- name: Check go version
  shell: >
    source /root/.bashrc && \
    go version
  register: go_version_check
  environment:
    PATH: "{{ extended_path }}"

- name: Debug go version
  debug:
    msg: "{{ go_version_check.stdout }} <-- go version"

- name: build cri-o
  shell: |
          source /root/.bashrc && \
          go version && \
          cd /root/src/github.com/kubernetes-incubator/cri-o && \
          make install.tools && \
          make && \
          make install && \
          make install.systemd && \
          make install.config
  environment:
    PATH: "{{ extended_path }}"

- name: build CNI stuff
  shell: |
          cd /root/src/github.com/containernetworking/plugins && \
          ./build.sh && \
          mkdir -p /opt/cni/bin && \
          cp bin/* /opt/cni/bin/
  environment:
    PATH: "{{ extended_path }}"

- name: run CRI-O with systemd cgroup manager
  replace:
    regexp: 'cgroupfs'
    replace: 'systemd'
    name: /etc/crio/crio.conf
    backup: yes

- name: run with overlay2
  replace:
    regexp: 'storage_driver = ""'
    replace: 'storage_driver = "overlay2"'
    name: /etc/crio/crio.conf
    backup: yes

- name: add overlay2 storage opts on RHEL/CentOS
  lineinfile:
    dest: /etc/crio/crio.conf
    line: '"overlay2.override_kernel_check=1"'
    insertafter: 'storage_option = \['
    regexp: 'overlay2\.override_kernel_check=1'
    state: present

- name: enable and start CRI-O
  systemd:
    name: crio
    state: started
    enabled: yes
    daemon_reload: yes

- name: modprobe br_netfilter
  command: "modprobe br_netfilter"
  ignore_errors: true

- name: tune sysctl
  lineinfile:
    line: "net/bridge/bridge-nf-call-iptables = 1"
    dest: /etc/sysctl.conf
    insertafter: 'EOF'
    regexp: '\/net\/bridge\/bridge-nf-call-iptables = 1'
    state: present
  ignore_errors: true

- name: reload sysctl
  command: "sysctl -p"
  ignore_errors: true

- name: systemd dropin for kubeadm
  shell: |
          sh -c 'echo "[Service]
          Environment=\"KUBELET_EXTRA_ARGS=--container-runtime=remote --runtime-request-timeout=15m --image-service-endpoint /var/run/crio.sock --container-runtime-endpoint /var/run/crio.sock\"" > /etc/systemd/system/kubelet.service.d/0-crio.conf'

- name: flush iptables
  command: "iptables -F"

# - name: Permanently disable selinux
#   lineinfile:
#     dest: /etc/selinux/config
#     line: 'SELINUX=permissive'
#     regexp: '^SELINUX='
#   when: (ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS')

# - name: disable selinux
#   command: "setenforce 0"
#   when: (ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS')
