---
- import_playbook: ka-init/init.yml

- hosts: virthost
  tasks:
    - name: Reload dnsmasq config, so that VM's DNS cache can be refreshed.
      block:
        - debug:
            msg: "Reloading dnsmasq config."
        - name: Reload dnsmasq config
          command: pkill -HUP dnsmasq
      tags: dns-workaround

  roles:
    - { role: redhat-nfvpe.vm-spinup }
