# Creates a systemd unit and starts kubectl proxy.
# https://kubernetes.io/docs/user-guide/kubectl/v1.8/#proxy

- name: Install jq binary
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/bin/jq

- name: set jq binary permission
  file:
    path: /usr/bin/jq
    mode: 0755

- name: Template kubectl proxy systemd unit
  template:
    src: kubectl-proxy.service.j2
    dest: /etc/systemd/system/kubectl-proxy.service
  register: template_kubectlproxy_unit

- name: Restart proxy when changed
  systemd:
    name: kubectl-proxy
    state: restarted
    daemon_reload: yes
  when: template_kubectlproxy_unit.changed

- name: Always ensure proxy is started
  systemd:
    name: kubectl-proxy
    state: started
    daemon_reload: yes
